# Generated by Django 4.0.4 on 2022-05-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=1),
        ),
    ]
